### ISSUE TITLE
Release v0 so that it can be used with `savi deps add Benchmark`

### ISSUE THREAD

**Issue by mneumann** [savi-lang/Benchmark#4]

**Comment by jemc** [comment]
As a regular contributor, you can feel free to tag releases whenever you need them.

- Use this page to create a new release from the latest commit: https://github.com/savi-lang/Benchmark/releases/new
- Use a tag name like `v0.20220911.0` - this is how I'm doing semver-ish versioning for pre-v1.0 releases. The minor number is the date and the patch number increments up from zero if I do multiple releases on the same day.
- Use the "Generate Release Notes" button that GitHub provides to list the changes, and tweak the output of that to be more or less verbose as desired.

For convenience, I'll go ahead and tag it this time.

**Comment by jemc** [comment]
Done: https://github.com/savi-lang/Benchmark/releases/tag/v0.20220911.0
