### ISSUE TITLE
Naming benchmarks `bench` or `benchmark`

### ISSUE THREAD

**Issue by mneumann** [savi-lang/Benchmark#8]
* The library is called `Benchmark` (vs. `Spec` for testing)
* I named benchmarks `JSON.Reader.Bench` (vs. `JSON.Reader.Benchmark`).
* I named the benchmark binary bench

To me `benchmark` / `Benchmark` reads just better and is more in line with the naming of `Spec` / `spec`.

When talking about benchmarks I would actually name it "a benchmark" and not "a bench".

**Comment by jemc** [comment]
Fair enough - I'm okay with that argument.

If you want to issue PRs to this repo and the JSON repo to clean that up before it gets too far spread to other repos, then that would be good :+1:
